import type { MenuSourceItem } from './menu-pure'

export const BASELINE_MENU_SOURCE_ITEMS: MenuSourceItem[] = [
  {
    id: BigInt(1),
    parentId: null,
    code: 'dashboard',
    labelMs: 'Dashboard Utama',
    labelEn: 'Main Dashboard',
    route: '/dashboard',
    icon: 'dashboard',
    sortOrder: 1,
    active: true,
    roleIds: [BigInt(1), BigInt(2), BigInt(3), BigInt(4), BigInt(5)],
  },
  {
    id: BigInt(2),
    parentId: null,
    code: 'permohonan',
    labelMs: 'Modul Permohonan',
    labelEn: 'Application Module',
    route: null,
    icon: 'permohonan',
    sortOrder: 2,
    active: true,
    roleIds: [BigInt(1), BigInt(2), BigInt(3), BigInt(4), BigInt(5)],
  },
  {
    id: BigInt(21),
    parentId: BigInt(2),
    code: 'permohonan.senarai',
    labelMs: 'Senarai Permohonan',
    labelEn: 'Application List',
    route: '/permohonan',
    icon: 'permohonan',
    sortOrder: 1,
    active: true,
    roleIds: [BigInt(1), BigInt(2), BigInt(3), BigInt(4), BigInt(5)],
  },
  {
    id: BigInt(22),
    parentId: BigInt(2),
    code: 'permohonan.baru',
    labelMs: 'Borang Permohonan Baru',
    labelEn: 'New Application Form',
    route: '/permohonan/baru',
    icon: 'permohonan',
    sortOrder: 2,
    active: true,
    roleIds: [BigInt(1), BigInt(2), BigInt(5)], // Super Admin, Data Admin, End User
  },
  {
    id: BigInt(3),
    parentId: null,
    code: 'pelesenan',
    labelMs: 'Pelesenan & Permit',
    labelEn: 'Licences & Permits',
    route: '/pelesenan',
    icon: 'licence',
    sortOrder: 3,
    active: true,
    roleIds: [BigInt(1), BigInt(2), BigInt(3), BigInt(4), BigInt(5)],
  },
  {
    id: BigInt(4),
    parentId: null,
    code: 'pekeliling',
    labelMs: 'Pekeliling & Notis',
    labelEn: 'Circulars & Notices',
    route: '/pekeliling',
    icon: 'pekeliling',
    sortOrder: 4,
    active: true,
    roleIds: [BigInt(1), BigInt(2), BigInt(3), BigInt(4), BigInt(5)],
  },
  {
    id: BigInt(5),
    parentId: null,
    code: 'audit',
    labelMs: 'Jejak Audit Sistem',
    labelEn: 'System Audit Trail',
    route: '/audit',
    icon: 'audit',
    sortOrder: 5,
    active: true,
    roleIds: [BigInt(1), BigInt(2)], // Super Admin & Data Admin
  },
  {
    id: BigInt(6),
    parentId: null,
    code: 'tetapan',
    labelMs: 'Tetapan & Konfigurasi',
    labelEn: 'Settings & Configuration',
    route: '/tetapan',
    icon: 'settings',
    sortOrder: 6,
    active: true,
    roleIds: [BigInt(1)], // Super Admin only
  },
]
